# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=30)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lograd', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='espaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_endereco', models.CharField(max_length=500)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('valor_hora', models.FloatField()),
                ('disponib', models.BooleanField()),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.item')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name=5000)),
                ('status', models.CharField(max_length=50)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.pacote')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa_comum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.curso')),
            ],
        ),
        migrations.CreateModel(
            name='recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.item')),
            ],
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.item')),
            ],
        ),
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tecnico_cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nasc_data', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='usuario_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('acesso_nivel', models.SmallIntegerField()),
                ('criacao_data', models.DateField(auto_now_add=True)),
                ('modificacao_data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario_status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario_tipo'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.tecnico_cargo'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario'),
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario'),
        ),
        migrations.AddField(
            model_name='pessoa_comum',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.item'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.item'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoHere_site.usuario'),
        ),
    ]
